---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
  namespace: academia-de-dados
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
        - name: pgsql
          image: postgres:14.7
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: environments
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: environments
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgsql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql-pvc
      restartPolicy: Always
