---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environments
  namespace: academia-de-dados
data:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "${POSTGRES_DB}"
  DATABASE_URI: "${DATABASE_URI}"
  DATABASE_TESTS: "${DATABASE_TESTS}"
  DSN_SENTRY: "${DSN_SENTRY}"
  SECRET_KEY: "${SECRET_KEY}"
  ALGORITHM: "${ALGORITHM}"
  TIPO_DE_CRIPTOGRAFIA: "${TIPO_DE_CRIPTOGRAFIA}"
  TEMPO_DE_EXPIRACAO: "${TEMPO_DE_EXPIRACAO}"
