---
apiVersion: v1
kind: Service
metadata:
  name: app-backend
  labels:
    app: app-backend
spec:
  selector:
    app: app-backend
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
